import os
from dotenv import load_dotenv
from google import genai


class GeminiClient:
    def __init__(self, model_name="gemini-2.5-flash"):
        load_dotenv()

        api_key = os.getenv("GEMINI_API_KEY")

        if not api_key:
            raise ValueError("No se encontró GEMINI_API_KEY en el archivo .env")

        self.client = genai.Client(api_key=api_key)
        self.model_name = model_name

    def generate_response(self, prompt):
        response = self.client.models.generate_content(
            model=self.model_name,
            contents=prompt
        )

        if response.text:
            return response.text

        return "No response generated by Gemini."