from pathlib import Path
from strands import tool


MEMORY_DIR = Path("memory")


@tool
def save_agent_output(agent_name: str, content: str) -> str:
    """
    Save an agent output into shared memory.

    Args:
        agent_name: Name of the agent.
        content: Content generated by the agent.

    Returns:
        Confirmation message with the saved file path.
    """
    MEMORY_DIR.mkdir(exist_ok=True)

    filename = f"{agent_name.lower().replace(' ', '_')}.md"
    file_path = MEMORY_DIR / filename

    with open(file_path, "w", encoding="utf-8") as file:
        file.write(content)

    return f"Saved output for {agent_name} at {file_path}"


@tool
def read_agent_output(agent_name: str) -> str:
    """
    Read an agent output from shared memory.

    Args:
        agent_name: Name of the agent.

    Returns:
        Saved content or an error message.
    """
    filename = f"{agent_name.lower().replace(' ', '_')}.md"
    file_path = MEMORY_DIR / filename

    if not file_path.exists():
        return f"No saved output found for {agent_name}"

    return file_path.read_text(encoding="utf-8")